//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AcAnalysisHeadAllocation
    {
        public int AcAnalysisHeadAllocationID { get; set; }
        public Nullable<int> AcjournalDetailID { get; set; }
        public Nullable<int> AnalysisHeadID { get; set; }
        public Nullable<decimal> Amount { get; set; }
    }
}
