//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AcCategory
    {
        public AcCategory()
        {
            this.AcGroups = new HashSet<AcGroup>();
        }
    
        public int AcCategoryID { get; set; }
        public string AcCategory1 { get; set; }
        public Nullable<int> CategoryOrder { get; set; }
    
        public virtual ICollection<AcGroup> AcGroups { get; set; }
    }
}
