//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AcGroup
    {
        public int AcGroupID { get; set; }
        public Nullable<int> AcBranchID { get; set; }
        public string AcGroup1 { get; set; }
        public string AcType { get; set; }
        public string AcClass { get; set; }
        public Nullable<int> ParentID { get; set; }
        public Nullable<int> GroupOrder { get; set; }
        public Nullable<short> StaticEdit { get; set; }
        public Nullable<bool> StatusHide { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> AcCategoryID { get; set; }
        public string GroupCode { get; set; }
        public Nullable<int> AcTypeId { get; set; }
    
        public virtual AcCategory AcCategory { get; set; }
    }
}
