//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AcHeadAssign
    {
        public int ID { get; set; }
        public Nullable<int> ProvisionCostControlAcID { get; set; }
        public Nullable<int> AccruedCostControlAcID { get; set; }
        public Nullable<int> OpenJobRevenueAcID { get; set; }
        public Nullable<int> CustomerControlAcID { get; set; }
        public Nullable<int> CashControlAcID { get; set; }
        public Nullable<int> SupplierControlAcID { get; set; }
    }
}
