//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AcHeadControl
    {
        public long Id { get; set; }
        public Nullable<int> Pagecontrol { get; set; }
        public Nullable<int> AccountControlHead { get; set; }
        public string AccountName { get; set; }
        public Nullable<int> AccountHeadID { get; set; }
        public Nullable<bool> AccountNature { get; set; }
        public Nullable<int> Remarks { get; set; }
        public Nullable<bool> CheckSum { get; set; }
    }
}
