//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AcHeadNew
    {
        public int AcHeadNewID { get; set; }
        public string AcHeadKey { get; set; }
        public string AccountCode { get; set; }
        public string AcHead { get; set; }
        public Nullable<int> AcGroupID { get; set; }
    }
}
