//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AcHead
    {
        public int AcHeadID { get; set; }
        public string AcHeadKey { get; set; }
        public string AcHead1 { get; set; }
        public Nullable<int> AcGroupID { get; set; }
        public Nullable<int> ParentID { get; set; }
        public Nullable<int> HeadOrder { get; set; }
        public Nullable<bool> StatusHide { get; set; }
        public Nullable<int> UserID { get; set; }
        public string Prefix { get; set; }
        public Nullable<bool> StatusControlAC { get; set; }
        public string AccountDescription { get; set; }
        public Nullable<int> AcBranchID { get; set; }
        public Nullable<decimal> TaxPercent { get; set; }
        public bool TaxApplicable { get; set; }
    
        public virtual AcGroup AcGroup { get; set; }
    }
}
