//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AcInventoryMaster
    {
        public int AcInventoryMasterID { get; set; }
        public Nullable<int> AcJournalID { get; set; }
        public string InvoiceNo { get; set; }
        public string StatusInventory { get; set; }
        public Nullable<bool> StatusCredit { get; set; }
        public Nullable<int> AcBankDetailID { get; set; }
        public Nullable<bool> StatusClose { get; set; }
    }
}
