//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AcJournalMaster
    {
        public AcJournalMaster()
        {
            this.AcJournalDetails = new HashSet<AcJournalDetail>();
        }
    
        public int AcJournalID { get; set; }
        public string VoucherNo { get; set; }
        public Nullable<System.DateTime> TransDate { get; set; }
        public Nullable<int> AcFinancialYearID { get; set; }
        public string VoucherType { get; set; }
        public Nullable<short> TransType { get; set; }
        public Nullable<bool> StatusDelete { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> ShiftID { get; set; }
        public Nullable<int> AcCompanyID { get; set; }
        public string Reference { get; set; }
        public Nullable<int> PaymentType { get; set; }
        public Nullable<bool> Lock { get; set; }
        public string TransactionNo { get; set; }
        public int ID { get; set; }
    
        public virtual ICollection<AcJournalDetail> AcJournalDetails { get; set; }
    }
}
