//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AcLedger
    {
        public int AcLedgerID { get; set; }
        public Nullable<int> AcHeadID { get; set; }
        public Nullable<System.DateTime> TransDate { get; set; }
        public Nullable<System.DateTime> PostedDate { get; set; }
        public Nullable<decimal> TotalDrAmt { get; set; }
        public Nullable<decimal> TotalCrAmt { get; set; }
        public Nullable<int> AcFinancialYearID { get; set; }
        public string Remarks { get; set; }
    }
}
