//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AcTransLog
    {
        public int AcTransLogID { get; set; }
        public Nullable<int> AccID { get; set; }
        public string FieldName { get; set; }
        public string TableName { get; set; }
        public Nullable<System.DateTime> TransDate { get; set; }
        public Nullable<double> Amount { get; set; }
        public string StatusAction { get; set; }
        public Nullable<System.DateTime> LogDate { get; set; }
        public Nullable<int> UserID { get; set; }
    }
}
