//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdditionalCost
    {
        public int AdditionalCostID { get; set; }
        public string AdditionalCost1 { get; set; }
        public string AdditionalCostCalculation { get; set; }
        public Nullable<int> AcHeadID { get; set; }
    }
}
