//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnalysisGroup
    {
        public AnalysisGroup()
        {
            this.AnalysisHeads = new HashSet<AnalysisHead>();
        }
    
        public int AnalysisGroupID { get; set; }
        public string AnalysisGroup1 { get; set; }
    
        public virtual ICollection<AnalysisHead> AnalysisHeads { get; set; }
    }
}
