//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BranchMaster
    {
        public int BranchID { get; set; }
        public string BranchName { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public Nullable<int> CountryID { get; set; }
        public Nullable<int> CityID { get; set; }
        public Nullable<int> LocationID { get; set; }
        public string KeyPerson { get; set; }
        public Nullable<int> DesignationID { get; set; }
        public string Phone { get; set; }
        public string PhoneNo1 { get; set; }
        public string PhoneNo2 { get; set; }
        public string PhoneNo3 { get; set; }
        public string PhoneNo4 { get; set; }
        public string MobileNo1 { get; set; }
        public string MobileNo2 { get; set; }
        public string EMail { get; set; }
        public string Website { get; set; }
        public string BranchPrefix { get; set; }
        public Nullable<int> CurrencyID { get; set; }
        public Nullable<int> AcCompanyID { get; set; }
        public Nullable<bool> StatusAssociate { get; set; }
        public string City { get; set; }
        public string ContactPerson { get; set; }
    
        public virtual CountryMaster CountryMaster { get; set; }
        public virtual CurrencyMaster CurrencyMaster { get; set; }
        public virtual Designation Designation { get; set; }
        public virtual Location Location { get; set; }
    }
}
