//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BudgetDetail
    {
        public int BudgetDetailID { get; set; }
        public Nullable<int> BudgetID { get; set; }
        public Nullable<int> PeriodID { get; set; }
        public Nullable<int> AcHeadID { get; set; }
        public Nullable<decimal> Amount { get; set; }
    }
}
