//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Budget
    {
        public int BudgetID { get; set; }
        public Nullable<System.DateTime> BudgetDate { get; set; }
        public Nullable<int> PeriodTypeID { get; set; }
        public string BudgetName { get; set; }
        public string StatusBudget { get; set; }
    }
}
