//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CECargoDescription
    {
        public int CargoDescriptionID { get; set; }
        public Nullable<int> CustomerEnquiryID { get; set; }
        public string Mark { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> weight { get; set; }
        public Nullable<decimal> volume { get; set; }
        public Nullable<decimal> Packages { get; set; }
        public Nullable<decimal> GrossWeight { get; set; }
    }
}
