//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CollectionNote
    {
        public int CollectionNoteID { get; set; }
        public Nullable<int> CollectionPointID { get; set; }
        public Nullable<int> TransportCompanyID { get; set; }
        public Nullable<int> DeliveryPointID { get; set; }
        public Nullable<System.DateTime> CollectionDate { get; set; }
        public string MarksAndNos { get; set; }
        public string CargoDescription { get; set; }
        public string Volume { get; set; }
        public Nullable<double> Weight { get; set; }
        public Nullable<int> JobID { get; set; }
    }
}
