//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContainerDetail
    {
        public int ContainerDetailID { get; set; }
        public Nullable<int> ContainerID { get; set; }
        public string SealNo { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> NoOfPackages { get; set; }
        public Nullable<double> Weight { get; set; }
        public string Volume { get; set; }
    }
}
