//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CostUpdationDetail
    {
        public int CostUpdationDetailID { get; set; }
        public Nullable<int> CostUpdationID { get; set; }
        public Nullable<int> RevenueTypeID { get; set; }
        public Nullable<int> ProvisionCurrencyID { get; set; }
        public Nullable<decimal> ProvisionExchangeRate { get; set; }
        public Nullable<decimal> ProvisionForeign { get; set; }
        public Nullable<decimal> ProvisionHome { get; set; }
        public Nullable<int> SalesCurrencyID { get; set; }
        public Nullable<decimal> SalesExchangeRate { get; set; }
        public Nullable<decimal> SalesForeign { get; set; }
        public Nullable<decimal> SalesHome { get; set; }
        public Nullable<decimal> Variance { get; set; }
        public Nullable<int> SupplierID { get; set; }
        public Nullable<int> JInvoiceID { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<int> PrevCostDetailID { get; set; }
        public Nullable<decimal> AmountPaidTillDate { get; set; }
        public string PaidOrNot { get; set; }
        public string SupplierReference { get; set; }
        public string SupplierPayStatus { get; set; }
        public Nullable<bool> Lock { get; set; }
    }
}
