//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CostUpdation
    {
        public int CostUpdationID { get; set; }
        public Nullable<int> SupplierID { get; set; }
        public Nullable<int> JobID { get; set; }
        public string InvoiceNo { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public Nullable<int> AcJournalID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public string DocumentNo { get; set; }
        public Nullable<int> PrevCostupID { get; set; }
        public string SupplierPaymentStatus { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<bool> Lock { get; set; }
        public Nullable<decimal> InvoiceAmount { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
    }
}
