//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerInvoice
    {
        public int CustomerInvoiceID { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public string DocumentNo { get; set; }
        public Nullable<int> QuotationID { get; set; }
        public string Remarks { get; set; }
    }
}
