//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomsDocument
    {
        public int CustomsDocumentID { get; set; }
        public Nullable<int> ShipperID { get; set; }
        public Nullable<int> VesselID { get; set; }
        public Nullable<int> VoyageID { get; set; }
        public Nullable<int> ShippingAgentID { get; set; }
        public Nullable<int> ClearingAgentID { get; set; }
        public Nullable<int> CIFValue { get; set; }
        public Nullable<int> ContainerTypeID { get; set; }
        public string CargoDescription { get; set; }
        public Nullable<int> OrignID { get; set; }
        public Nullable<int> DestinationID { get; set; }
        public string Volume { get; set; }
        public Nullable<double> Weight { get; set; }
        public Nullable<int> ShippingInstructionID { get; set; }
    }
}
