//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerNotification
    {
        public int Id { get; set; }
        public Nullable<int> StaffId { get; set; }
        public Nullable<System.DateTime> Datetime { get; set; }
        public string Message { get; set; }
        public Nullable<int> JobId { get; set; }
        public Nullable<bool> IsEmail { get; set; }
        public Nullable<bool> IsSms { get; set; }
        public Nullable<bool> IsWhatsapp { get; set; }
        public Nullable<int> PageTypeId { get; set; }
    }
}
