//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerInvoiceDetail
    {
        public int CustomerInvoiceDetailID { get; set; }
        public Nullable<int> CustomerInvoiceID { get; set; }
        public Nullable<int> RevenueTypeID { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> ExchangeRate { get; set; }
        public Nullable<int> CurrencyID { get; set; }
        public Nullable<int> SupplierID { get; set; }
        public Nullable<decimal> SupplierAmt { get; set; }
        public Nullable<int> SupplierCurrencyID { get; set; }
        public Nullable<decimal> SupplierExchangeRate { get; set; }
        public Nullable<int> QuotationDetailID { get; set; }
        public string Remarks { get; set; }
    }
}
