//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DebitNote
    {
        public int DebitNoteID { get; set; }
        public string DebitNoteNo { get; set; }
        public Nullable<int> InvoiceID { get; set; }
        public Nullable<System.DateTime> DebitNoteDate { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<int> AcJournalID { get; set; }
        public Nullable<int> FYearID { get; set; }
        public Nullable<int> AcCompanyID { get; set; }
        public string InvoiceType { get; set; }
        public Nullable<int> RecPayID { get; set; }
        public Nullable<int> AcHeadID { get; set; }
        public Nullable<int> SupplierID { get; set; }
        public Nullable<bool> IsShipping { get; set; }
    }
}
