//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentTemplateSale
    {
        public int DocumentTemplateSalesID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public string PaymentTerms { get; set; }
        public string QuotationValidity { get; set; }
        public Nullable<int> ValidityDays { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> CurrencyID { get; set; }
        public Nullable<bool> StatusDiscount { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public string StatusDocument { get; set; }
    }
}
