//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int EmployeeID { get; set; }
        public string EmployeeName { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public string ContactNo { get; set; }
        public Nullable<int> DesignationID { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public Nullable<int> LocationID { get; set; }
        public string Nationality { get; set; }
        public Nullable<System.DateTime> DOJ { get; set; }
        public Nullable<bool> StatusActive { get; set; }
        public Nullable<System.DateTime> DOL { get; set; }
        public Nullable<decimal> Basic { get; set; }
        public Nullable<decimal> Housing { get; set; }
        public Nullable<decimal> TA { get; set; }
        public string Email { get; set; }
    }
}
