//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemUnit
    {
        public int ItemUnitID { get; set; }
        public string ItemUnit1 { get; set; }
        public Nullable<int> EqualentQty { get; set; }
        public Nullable<bool> StatusActive { get; set; }
        public string Remarks { get; set; }
    }
}
