//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobEnquiry
    {
        public int Id { get; set; }
        public string EnquiryNo { get; set; }
        public Nullable<System.DateTime> EnquiryDate { get; set; }
        public string EnquiryType { get; set; }
        public string LoadPort { get; set; }
        public string DestinationPort { get; set; }
        public string ReceiptPlace { get; set; }
        public string DeliveryPlace { get; set; }
        public string Shipper { get; set; }
        public string Consignee { get; set; }
        public string InvoiceTo { get; set; }
        public string NotifyTo { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> BranchId { get; set; }
    }
}
