//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobType
    {
        public int JobTypeID { get; set; }
        public string JobDescription { get; set; }
        public Nullable<int> JobModeID { get; set; }
        public string Remarks { get; set; }
        public string JobCode { get; set; }
        public string JobPrefix { get; set; }
        public Nullable<bool> StatusSea { get; set; }
        public Nullable<bool> ShowDisplay { get; set; }
    }
}
