//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Location
    {
        public Location()
        {
            this.BranchMasters = new HashSet<BranchMaster>();
            this.AcCompanies = new HashSet<AcCompany>();
        }
    
        public int LocationID { get; set; }
        public string Location1 { get; set; }
        public string prefix { get; set; }
        public string Country { get; set; }
    
        public virtual ICollection<BranchMaster> BranchMasters { get; set; }
        public virtual ICollection<AcCompany> AcCompanies { get; set; }
    }
}
