//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Port
    {
        public int PortID { get; set; }
        public string PortCode { get; set; }
        public string Port1 { get; set; }
        public Nullable<int> CountryID { get; set; }
    }
}
