//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseInvoiceDetail
    {
        public int PurchaseInvoiceDetailID { get; set; }
        public Nullable<int> PurchaseInvoiceID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> ItemUnitID { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<decimal> RateFC { get; set; }
        public Nullable<decimal> Value { get; set; }
        public Nullable<decimal> ValueFC { get; set; }
        public Nullable<decimal> Taxprec { get; set; }
        public Nullable<decimal> Tax { get; set; }
        public Nullable<decimal> NetValue { get; set; }
        public Nullable<int> AcHeadID { get; set; }
        public Nullable<int> JobID { get; set; }
        public string Description { get; set; }
        public Nullable<int> RecPayStatus { get; set; }
        public Nullable<int> RecPayDetailId { get; set; }
    }
}
