//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class QContainerDetail
    {
        public int CEContainerDetailID { get; set; }
        public Nullable<int> QuotationID { get; set; }
        public Nullable<int> ContainerTypeID { get; set; }
        public string ContainerNo { get; set; }
        public string SealNo { get; set; }
        public string Description { get; set; }
    }
}
