//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecPayAdvanceAllocation
    {
        public int RecPayAdvanceAllocationID { get; set; }
        public Nullable<System.DateTime> AllocatedDate { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<int> BusinessCentreID { get; set; }
        public Nullable<int> SupplierID { get; set; }
        public Nullable<decimal> AllocatedAmount { get; set; }
    }
}
