//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class RevenueType
    {
        public int RevenueTypeID { get; set; }
        public string RevenueType1 { get; set; }
        public Nullable<int> AcHeadID { get; set; }
        public string RevenueCode { get; set; }
        public Nullable<decimal> RevenueCost { get; set; }
        public Nullable<decimal> MinimumValue { get; set; }
        public Nullable<decimal> TaxPercentage { get; set; }
    }
}
