//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Route
    {
        public int RouteID { get; set; }
        public string RouteCode { get; set; }
        public string Route1 { get; set; }
        public Nullable<int> OriginPortID { get; set; }
        public Nullable<int> DestinationPortID { get; set; }
    }
}
