//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesInvoice
    {
        public int SalesInvoiceID { get; set; }
        public string SalesInvoiceNo { get; set; }
        public Nullable<System.DateTime> SalesInvoiceDate { get; set; }
        public string QuotationNumber { get; set; }
        public string Reference { get; set; }
        public string LPOReference { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<int> CurrencyID { get; set; }
        public Nullable<decimal> ExchangeRate { get; set; }
        public Nullable<int> CreditDays { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<int> AcJournalID { get; set; }
        public Nullable<int> BranchID { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<bool> StatusDiscountAmt { get; set; }
        public Nullable<decimal> OtherCharges { get; set; }
        public string PaymentTerm { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> FYearID { get; set; }
        public Nullable<int> DeliveryId { get; set; }
        public Nullable<int> DiscountType { get; set; }
        public Nullable<decimal> DiscountValueLC { get; set; }
        public Nullable<decimal> DiscountValueFC { get; set; }
        public Nullable<bool> IsShipping { get; set; }
    }
}
