//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SeaFrightDetail
    {
        public int SeaFrightDetailID { get; set; }
        public Nullable<int> SeaFrightID { get; set; }
        public Nullable<int> FrightRateID { get; set; }
        public Nullable<int> CurrencyID { get; set; }
        public Nullable<decimal> ExchangeRate { get; set; }
        public Nullable<decimal> Foreign20 { get; set; }
        public Nullable<decimal> Home20 { get; set; }
        public Nullable<decimal> Foreign40 { get; set; }
        public Nullable<decimal> Home40 { get; set; }
        public Nullable<decimal> Foreign40HC { get; set; }
        public Nullable<decimal> Home40HC { get; set; }
    }
}
