//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShippingAgent
    {
        public int ShippingAgentID { get; set; }
        public string AgentName { get; set; }
        public string ReferenceCode { get; set; }
        public string ContactPerson { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string WebSite { get; set; }
        public Nullable<bool> StatusActive { get; set; }
        public Nullable<bool> StatusBlocked { get; set; }
        public Nullable<bool> StatusReserved { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> CountryID { get; set; }
        public string City { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public string ExportCode { get; set; }
        public Nullable<int> CreditLimit { get; set; }
        public Nullable<int> CreditDays { get; set; }
    }
}
