//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShippingInstruction
    {
        public int ShippingInstructionID { get; set; }
        public string DocumentNo { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> JobID { get; set; }
        public Nullable<System.DateTime> SailingDate { get; set; }
        public Nullable<int> ConsigneeID { get; set; }
        public Nullable<int> NotifyPartyID { get; set; }
    }
}
