//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockDetail
    {
        public int StockDetailID { get; set; }
        public Nullable<int> PurchaseInvoiceDetailID { get; set; }
        public Nullable<int> QTY { get; set; }
        public Nullable<int> CargoInscanID { get; set; }
        public Nullable<System.DateTime> StockDate { get; set; }
        public Nullable<int> SalesInvoiceDetailID { get; set; }
    }
}
