//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplierTypeMaster
    {
        public int SupplierTypeID { get; set; }
        public string SupplierCode { get; set; }
        public string SupplierType { get; set; }
        public Nullable<int> BranchId { get; set; }
    }
}
