//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplierRequest
    {
        public int SupplierRequestID { get; set; }
        public Nullable<System.DateTime> RequestDate { get; set; }
        public string DocumentNo { get; set; }
        public Nullable<int> SupplierID { get; set; }
        public Nullable<int> DeliveryPeriod { get; set; }
        public Nullable<int> DeliveryLocationID { get; set; }
        public string Remarks { get; set; }
        public string StatusDocument { get; set; }
        public Nullable<int> LocationID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<int> User1 { get; set; }
        public Nullable<double> Weight { get; set; }
        public string BookingConfirmationNo { get; set; }
        public Nullable<System.DateTime> BookingConfirmationDate { get; set; }
        public string ContainerReleaseNo { get; set; }
        public Nullable<int> CarrierID { get; set; }
        public Nullable<int> RouteID { get; set; }
        public Nullable<int> JobTypeID { get; set; }
        public Nullable<int> QuotationID { get; set; }
    }
}
