//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier
    {
        public int SupplierID { get; set; }
        public string SupplierName { get; set; }
        public string ReferenceCode { get; set; }
        public string ContactPerson { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string WebSite { get; set; }
        public Nullable<int> MaxCreditDays { get; set; }
        public Nullable<double> MaxCreditLimit { get; set; }
        public Nullable<bool> StatusActive { get; set; }
        public string Remarks { get; set; }
        public Nullable<bool> StatusReserved { get; set; }
        public string POBoxNo { get; set; }
        public Nullable<bool> statusInventory { get; set; }
        public string RevenuTypeIds { get; set; }
        public Nullable<int> CountryID { get; set; }
        public string City { get; set; }
        public Nullable<int> ExportCode { get; set; }
        public Nullable<int> CityID { get; set; }
        public Nullable<int> CurrencyID { get; set; }
        public Nullable<int> AcCompanyID { get; set; }
        public string MobileNo { get; set; }
        public Nullable<int> LocationID { get; set; }
        public Nullable<int> BranchID { get; set; }
        public Nullable<int> SupplierTypeID { get; set; }
        public Nullable<int> SupplierType { get; set; }
    }
}
