//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UMGroupAccess1
    {
        public int GAID { get; set; }
        public Nullable<int> GID { get; set; }
        public Nullable<int> FID { get; set; }
        public Nullable<bool> CanCreate { get; set; }
        public Nullable<bool> CanModify { get; set; }
        public Nullable<bool> CanDelete { get; set; }
        public Nullable<bool> CanView { get; set; }
        public Nullable<int> User1 { get; set; }
    }
}
