//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;

    public partial class CostUpdationDetail
    {
        public string RevenueTypeName { get; set; }
        public string CurrencyName { get; set; }
        public decimal? InvoiceAmount { get; set; }
        public int JobID { get; set; }

    }
}
